#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewTest
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TestDB")]
	public partial class DCDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTbl_Sitestyle_Alert(Tbl_Sitestyle_Alert instance);
    partial void UpdateTbl_Sitestyle_Alert(Tbl_Sitestyle_Alert instance);
    partial void DeleteTbl_Sitestyle_Alert(Tbl_Sitestyle_Alert instance);
    partial void InsertTbl_Sitestyle_AlertLanguage(Tbl_Sitestyle_AlertLanguage instance);
    partial void UpdateTbl_Sitestyle_AlertLanguage(Tbl_Sitestyle_AlertLanguage instance);
    partial void DeleteTbl_Sitestyle_AlertLanguage(Tbl_Sitestyle_AlertLanguage instance);
    partial void InsertTbl_Sitestyle_Alerttype(Tbl_Sitestyle_Alerttype instance);
    partial void UpdateTbl_Sitestyle_Alerttype(Tbl_Sitestyle_Alerttype instance);
    partial void DeleteTbl_Sitestyle_Alerttype(Tbl_Sitestyle_Alerttype instance);
    partial void InsertTbl_Sitestyle_Css(Tbl_Sitestyle_Css instance);
    partial void UpdateTbl_Sitestyle_Css(Tbl_Sitestyle_Css instance);
    partial void DeleteTbl_Sitestyle_Css(Tbl_Sitestyle_Css instance);
    partial void InsertTbl_Sitestyle_Font(Tbl_Sitestyle_Font instance);
    partial void UpdateTbl_Sitestyle_Font(Tbl_Sitestyle_Font instance);
    partial void DeleteTbl_Sitestyle_Font(Tbl_Sitestyle_Font instance);
    partial void InsertTbl_Sitestyle_Iso639_1(Tbl_Sitestyle_Iso639_1 instance);
    partial void UpdateTbl_Sitestyle_Iso639_1(Tbl_Sitestyle_Iso639_1 instance);
    partial void DeleteTbl_Sitestyle_Iso639_1(Tbl_Sitestyle_Iso639_1 instance);
    partial void InsertTbl_Sitestyle_Iso639_2(Tbl_Sitestyle_Iso639_2 instance);
    partial void UpdateTbl_Sitestyle_Iso639_2(Tbl_Sitestyle_Iso639_2 instance);
    partial void DeleteTbl_Sitestyle_Iso639_2(Tbl_Sitestyle_Iso639_2 instance);
    partial void InsertTbl_Sitestyle_Iso639_3(Tbl_Sitestyle_Iso639_3 instance);
    partial void UpdateTbl_Sitestyle_Iso639_3(Tbl_Sitestyle_Iso639_3 instance);
    partial void DeleteTbl_Sitestyle_Iso639_3(Tbl_Sitestyle_Iso639_3 instance);
    partial void InsertTbl_Sitestyle_Language(Tbl_Sitestyle_Language instance);
    partial void UpdateTbl_Sitestyle_Language(Tbl_Sitestyle_Language instance);
    partial void DeleteTbl_Sitestyle_Language(Tbl_Sitestyle_Language instance);
    partial void InsertTbl_Sitestyle_Menu(Tbl_Sitestyle_Menu instance);
    partial void UpdateTbl_Sitestyle_Menu(Tbl_Sitestyle_Menu instance);
    partial void DeleteTbl_Sitestyle_Menu(Tbl_Sitestyle_Menu instance);
    partial void InsertTbl_Sitestyle_MenuLanguage(Tbl_Sitestyle_MenuLanguage instance);
    partial void UpdateTbl_Sitestyle_MenuLanguage(Tbl_Sitestyle_MenuLanguage instance);
    partial void DeleteTbl_Sitestyle_MenuLanguage(Tbl_Sitestyle_MenuLanguage instance);
    partial void InsertTbl_Sitestyle_Metadata(Tbl_Sitestyle_Metadata instance);
    partial void UpdateTbl_Sitestyle_Metadata(Tbl_Sitestyle_Metadata instance);
    partial void DeleteTbl_Sitestyle_Metadata(Tbl_Sitestyle_Metadata instance);
    partial void InsertTbl_Users_UsersActivityGroup(Tbl_Users_UsersActivityGroup instance);
    partial void UpdateTbl_Users_UsersActivityGroup(Tbl_Users_UsersActivityGroup instance);
    partial void DeleteTbl_Users_UsersActivityGroup(Tbl_Users_UsersActivityGroup instance);
    partial void InsertTbl_Users_UsersActivityGroupLanguage(Tbl_Users_UsersActivityGroupLanguage instance);
    partial void UpdateTbl_Users_UsersActivityGroupLanguage(Tbl_Users_UsersActivityGroupLanguage instance);
    partial void DeleteTbl_Users_UsersActivityGroupLanguage(Tbl_Users_UsersActivityGroupLanguage instance);
    #endregion
		
		public DCDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TestDBConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DCDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DCDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tbl_Sitestyle_Alert> Tbl_Sitestyle_Alerts
		{
			get
			{
				return this.GetTable<Tbl_Sitestyle_Alert>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Sitestyle_AlertLanguage> Tbl_Sitestyle_AlertLanguages
		{
			get
			{
				return this.GetTable<Tbl_Sitestyle_AlertLanguage>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Sitestyle_Alerttype> Tbl_Sitestyle_Alerttypes
		{
			get
			{
				return this.GetTable<Tbl_Sitestyle_Alerttype>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Sitestyle_Css> Tbl_Sitestyle_Csses
		{
			get
			{
				return this.GetTable<Tbl_Sitestyle_Css>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Sitestyle_Font> Tbl_Sitestyle_Fonts
		{
			get
			{
				return this.GetTable<Tbl_Sitestyle_Font>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Sitestyle_Iso639_1> Tbl_Sitestyle_Iso639_1s
		{
			get
			{
				return this.GetTable<Tbl_Sitestyle_Iso639_1>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Sitestyle_Iso639_2> Tbl_Sitestyle_Iso639_2s
		{
			get
			{
				return this.GetTable<Tbl_Sitestyle_Iso639_2>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Sitestyle_Iso639_3> Tbl_Sitestyle_Iso639_3s
		{
			get
			{
				return this.GetTable<Tbl_Sitestyle_Iso639_3>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Sitestyle_Language> Tbl_Sitestyle_Languages
		{
			get
			{
				return this.GetTable<Tbl_Sitestyle_Language>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Sitestyle_Menu> Tbl_Sitestyle_Menus
		{
			get
			{
				return this.GetTable<Tbl_Sitestyle_Menu>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Sitestyle_MenuLanguage> Tbl_Sitestyle_MenuLanguages
		{
			get
			{
				return this.GetTable<Tbl_Sitestyle_MenuLanguage>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Sitestyle_Metadata> Tbl_Sitestyle_Metadatas
		{
			get
			{
				return this.GetTable<Tbl_Sitestyle_Metadata>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Users_UsersActivityGroup> Tbl_Users_UsersActivityGroups
		{
			get
			{
				return this.GetTable<Tbl_Users_UsersActivityGroup>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Users_UsersActivityGroupLanguage> Tbl_Users_UsersActivityGroupLanguages
		{
			get
			{
				return this.GetTable<Tbl_Users_UsersActivityGroupLanguage>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Sitestyle_Alert")]
	public partial class Tbl_Sitestyle_Alert : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Fld_Sitestyle_Alert_Id;
		
		private string _Fld_Sitestyle_Alert_Title;
		
		private string _Fld_Sitestyle_Alert_Code;
		
		private int _Fld_Sitestyle_Alert_AlerttypeId;
		
		private EntitySet<Tbl_Sitestyle_AlertLanguage> _Tbl_Sitestyle_AlertLanguages;
		
		private EntityRef<Tbl_Sitestyle_Alerttype> _Tbl_Sitestyle_Alerttype;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFld_Sitestyle_Alert_IdChanging(int value);
    partial void OnFld_Sitestyle_Alert_IdChanged();
    partial void OnFld_Sitestyle_Alert_TitleChanging(string value);
    partial void OnFld_Sitestyle_Alert_TitleChanged();
    partial void OnFld_Sitestyle_Alert_CodeChanging(string value);
    partial void OnFld_Sitestyle_Alert_CodeChanged();
    partial void OnFld_Sitestyle_Alert_AlerttypeIdChanging(int value);
    partial void OnFld_Sitestyle_Alert_AlerttypeIdChanged();
    #endregion
		
		public Tbl_Sitestyle_Alert()
		{
			this._Tbl_Sitestyle_AlertLanguages = new EntitySet<Tbl_Sitestyle_AlertLanguage>(new Action<Tbl_Sitestyle_AlertLanguage>(this.attach_Tbl_Sitestyle_AlertLanguages), new Action<Tbl_Sitestyle_AlertLanguage>(this.detach_Tbl_Sitestyle_AlertLanguages));
			this._Tbl_Sitestyle_Alerttype = default(EntityRef<Tbl_Sitestyle_Alerttype>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_Alert_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Fld_Sitestyle_Alert_Id
		{
			get
			{
				return this._Fld_Sitestyle_Alert_Id;
			}
			set
			{
				if ((this._Fld_Sitestyle_Alert_Id != value))
				{
					this.OnFld_Sitestyle_Alert_IdChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_Alert_Id = value;
					this.SendPropertyChanged("Fld_Sitestyle_Alert_Id");
					this.OnFld_Sitestyle_Alert_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_Alert_Title", DbType="NVarChar(MAX)")]
		public string Fld_Sitestyle_Alert_Title
		{
			get
			{
				return this._Fld_Sitestyle_Alert_Title;
			}
			set
			{
				if ((this._Fld_Sitestyle_Alert_Title != value))
				{
					this.OnFld_Sitestyle_Alert_TitleChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_Alert_Title = value;
					this.SendPropertyChanged("Fld_Sitestyle_Alert_Title");
					this.OnFld_Sitestyle_Alert_TitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_Alert_Code", DbType="NVarChar(MAX)")]
		public string Fld_Sitestyle_Alert_Code
		{
			get
			{
				return this._Fld_Sitestyle_Alert_Code;
			}
			set
			{
				if ((this._Fld_Sitestyle_Alert_Code != value))
				{
					this.OnFld_Sitestyle_Alert_CodeChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_Alert_Code = value;
					this.SendPropertyChanged("Fld_Sitestyle_Alert_Code");
					this.OnFld_Sitestyle_Alert_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_Alert_AlerttypeId", DbType="Int NOT NULL")]
		public int Fld_Sitestyle_Alert_AlerttypeId
		{
			get
			{
				return this._Fld_Sitestyle_Alert_AlerttypeId;
			}
			set
			{
				if ((this._Fld_Sitestyle_Alert_AlerttypeId != value))
				{
					if (this._Tbl_Sitestyle_Alerttype.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFld_Sitestyle_Alert_AlerttypeIdChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_Alert_AlerttypeId = value;
					this.SendPropertyChanged("Fld_Sitestyle_Alert_AlerttypeId");
					this.OnFld_Sitestyle_Alert_AlerttypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Sitestyle_Alert_Tbl_Sitestyle_AlertLanguage", Storage="_Tbl_Sitestyle_AlertLanguages", ThisKey="Fld_Sitestyle_Alert_Id", OtherKey="Fld_Sitestyle_AlertLanguage_AlertId")]
		public EntitySet<Tbl_Sitestyle_AlertLanguage> Tbl_Sitestyle_AlertLanguages
		{
			get
			{
				return this._Tbl_Sitestyle_AlertLanguages;
			}
			set
			{
				this._Tbl_Sitestyle_AlertLanguages.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Sitestyle_Alerttype_Tbl_Sitestyle_Alert", Storage="_Tbl_Sitestyle_Alerttype", ThisKey="Fld_Sitestyle_Alert_AlerttypeId", OtherKey="Fld_Sitestyle_Alerttype_Id", IsForeignKey=true)]
		public Tbl_Sitestyle_Alerttype Tbl_Sitestyle_Alerttype
		{
			get
			{
				return this._Tbl_Sitestyle_Alerttype.Entity;
			}
			set
			{
				Tbl_Sitestyle_Alerttype previousValue = this._Tbl_Sitestyle_Alerttype.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Sitestyle_Alerttype.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Sitestyle_Alerttype.Entity = null;
						previousValue.Tbl_Sitestyle_Alerts.Remove(this);
					}
					this._Tbl_Sitestyle_Alerttype.Entity = value;
					if ((value != null))
					{
						value.Tbl_Sitestyle_Alerts.Add(this);
						this._Fld_Sitestyle_Alert_AlerttypeId = value.Fld_Sitestyle_Alerttype_Id;
					}
					else
					{
						this._Fld_Sitestyle_Alert_AlerttypeId = default(int);
					}
					this.SendPropertyChanged("Tbl_Sitestyle_Alerttype");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Sitestyle_AlertLanguages(Tbl_Sitestyle_AlertLanguage entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Sitestyle_Alert = this;
		}
		
		private void detach_Tbl_Sitestyle_AlertLanguages(Tbl_Sitestyle_AlertLanguage entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Sitestyle_Alert = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Sitestyle_AlertLanguage")]
	public partial class Tbl_Sitestyle_AlertLanguage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Fld_Sitestyle_AlertLanguage_Id;
		
		private string _Fld_Sitestyle_AlertLanguage_Text;
		
		private string _Fld_Sitestyle_AlertLanguage_Title;
		
		private int _Fld_Sitestyle_AlertLanguage_AlertId;
		
		private int _Fld_Sitestyle_AlertLanguage_LanguageId;
		
		private EntityRef<Tbl_Sitestyle_Alert> _Tbl_Sitestyle_Alert;
		
		private EntityRef<Tbl_Sitestyle_Language> _Tbl_Sitestyle_Language;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFld_Sitestyle_AlertLanguage_IdChanging(int value);
    partial void OnFld_Sitestyle_AlertLanguage_IdChanged();
    partial void OnFld_Sitestyle_AlertLanguage_TextChanging(string value);
    partial void OnFld_Sitestyle_AlertLanguage_TextChanged();
    partial void OnFld_Sitestyle_AlertLanguage_TitleChanging(string value);
    partial void OnFld_Sitestyle_AlertLanguage_TitleChanged();
    partial void OnFld_Sitestyle_AlertLanguage_AlertIdChanging(int value);
    partial void OnFld_Sitestyle_AlertLanguage_AlertIdChanged();
    partial void OnFld_Sitestyle_AlertLanguage_LanguageIdChanging(int value);
    partial void OnFld_Sitestyle_AlertLanguage_LanguageIdChanged();
    #endregion
		
		public Tbl_Sitestyle_AlertLanguage()
		{
			this._Tbl_Sitestyle_Alert = default(EntityRef<Tbl_Sitestyle_Alert>);
			this._Tbl_Sitestyle_Language = default(EntityRef<Tbl_Sitestyle_Language>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_AlertLanguage_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Fld_Sitestyle_AlertLanguage_Id
		{
			get
			{
				return this._Fld_Sitestyle_AlertLanguage_Id;
			}
			set
			{
				if ((this._Fld_Sitestyle_AlertLanguage_Id != value))
				{
					this.OnFld_Sitestyle_AlertLanguage_IdChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_AlertLanguage_Id = value;
					this.SendPropertyChanged("Fld_Sitestyle_AlertLanguage_Id");
					this.OnFld_Sitestyle_AlertLanguage_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_AlertLanguage_Text", DbType="NVarChar(MAX)")]
		public string Fld_Sitestyle_AlertLanguage_Text
		{
			get
			{
				return this._Fld_Sitestyle_AlertLanguage_Text;
			}
			set
			{
				if ((this._Fld_Sitestyle_AlertLanguage_Text != value))
				{
					this.OnFld_Sitestyle_AlertLanguage_TextChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_AlertLanguage_Text = value;
					this.SendPropertyChanged("Fld_Sitestyle_AlertLanguage_Text");
					this.OnFld_Sitestyle_AlertLanguage_TextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_AlertLanguage_Title", DbType="NVarChar(MAX)")]
		public string Fld_Sitestyle_AlertLanguage_Title
		{
			get
			{
				return this._Fld_Sitestyle_AlertLanguage_Title;
			}
			set
			{
				if ((this._Fld_Sitestyle_AlertLanguage_Title != value))
				{
					this.OnFld_Sitestyle_AlertLanguage_TitleChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_AlertLanguage_Title = value;
					this.SendPropertyChanged("Fld_Sitestyle_AlertLanguage_Title");
					this.OnFld_Sitestyle_AlertLanguage_TitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_AlertLanguage_AlertId", DbType="Int NOT NULL")]
		public int Fld_Sitestyle_AlertLanguage_AlertId
		{
			get
			{
				return this._Fld_Sitestyle_AlertLanguage_AlertId;
			}
			set
			{
				if ((this._Fld_Sitestyle_AlertLanguage_AlertId != value))
				{
					if (this._Tbl_Sitestyle_Alert.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFld_Sitestyle_AlertLanguage_AlertIdChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_AlertLanguage_AlertId = value;
					this.SendPropertyChanged("Fld_Sitestyle_AlertLanguage_AlertId");
					this.OnFld_Sitestyle_AlertLanguage_AlertIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_AlertLanguage_LanguageId", DbType="Int NOT NULL")]
		public int Fld_Sitestyle_AlertLanguage_LanguageId
		{
			get
			{
				return this._Fld_Sitestyle_AlertLanguage_LanguageId;
			}
			set
			{
				if ((this._Fld_Sitestyle_AlertLanguage_LanguageId != value))
				{
					if (this._Tbl_Sitestyle_Language.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFld_Sitestyle_AlertLanguage_LanguageIdChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_AlertLanguage_LanguageId = value;
					this.SendPropertyChanged("Fld_Sitestyle_AlertLanguage_LanguageId");
					this.OnFld_Sitestyle_AlertLanguage_LanguageIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Sitestyle_Alert_Tbl_Sitestyle_AlertLanguage", Storage="_Tbl_Sitestyle_Alert", ThisKey="Fld_Sitestyle_AlertLanguage_AlertId", OtherKey="Fld_Sitestyle_Alert_Id", IsForeignKey=true)]
		public Tbl_Sitestyle_Alert Tbl_Sitestyle_Alert
		{
			get
			{
				return this._Tbl_Sitestyle_Alert.Entity;
			}
			set
			{
				Tbl_Sitestyle_Alert previousValue = this._Tbl_Sitestyle_Alert.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Sitestyle_Alert.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Sitestyle_Alert.Entity = null;
						previousValue.Tbl_Sitestyle_AlertLanguages.Remove(this);
					}
					this._Tbl_Sitestyle_Alert.Entity = value;
					if ((value != null))
					{
						value.Tbl_Sitestyle_AlertLanguages.Add(this);
						this._Fld_Sitestyle_AlertLanguage_AlertId = value.Fld_Sitestyle_Alert_Id;
					}
					else
					{
						this._Fld_Sitestyle_AlertLanguage_AlertId = default(int);
					}
					this.SendPropertyChanged("Tbl_Sitestyle_Alert");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Sitestyle_Language_Tbl_Sitestyle_AlertLanguage", Storage="_Tbl_Sitestyle_Language", ThisKey="Fld_Sitestyle_AlertLanguage_LanguageId", OtherKey="Fld_Sitestyle_Language_Id", IsForeignKey=true)]
		public Tbl_Sitestyle_Language Tbl_Sitestyle_Language
		{
			get
			{
				return this._Tbl_Sitestyle_Language.Entity;
			}
			set
			{
				Tbl_Sitestyle_Language previousValue = this._Tbl_Sitestyle_Language.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Sitestyle_Language.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Sitestyle_Language.Entity = null;
						previousValue.Tbl_Sitestyle_AlertLanguages.Remove(this);
					}
					this._Tbl_Sitestyle_Language.Entity = value;
					if ((value != null))
					{
						value.Tbl_Sitestyle_AlertLanguages.Add(this);
						this._Fld_Sitestyle_AlertLanguage_LanguageId = value.Fld_Sitestyle_Language_Id;
					}
					else
					{
						this._Fld_Sitestyle_AlertLanguage_LanguageId = default(int);
					}
					this.SendPropertyChanged("Tbl_Sitestyle_Language");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Sitestyle_Alerttype")]
	public partial class Tbl_Sitestyle_Alerttype : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Fld_Sitestyle_Alerttype_Id;
		
		private string _Fld_Sitestyle_Alerttype_Name;
		
		private string _Fld_Sitestyle_Alerttype_Icon;
		
		private EntitySet<Tbl_Sitestyle_Alert> _Tbl_Sitestyle_Alerts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFld_Sitestyle_Alerttype_IdChanging(int value);
    partial void OnFld_Sitestyle_Alerttype_IdChanged();
    partial void OnFld_Sitestyle_Alerttype_NameChanging(string value);
    partial void OnFld_Sitestyle_Alerttype_NameChanged();
    partial void OnFld_Sitestyle_Alerttype_IconChanging(string value);
    partial void OnFld_Sitestyle_Alerttype_IconChanged();
    #endregion
		
		public Tbl_Sitestyle_Alerttype()
		{
			this._Tbl_Sitestyle_Alerts = new EntitySet<Tbl_Sitestyle_Alert>(new Action<Tbl_Sitestyle_Alert>(this.attach_Tbl_Sitestyle_Alerts), new Action<Tbl_Sitestyle_Alert>(this.detach_Tbl_Sitestyle_Alerts));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_Alerttype_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Fld_Sitestyle_Alerttype_Id
		{
			get
			{
				return this._Fld_Sitestyle_Alerttype_Id;
			}
			set
			{
				if ((this._Fld_Sitestyle_Alerttype_Id != value))
				{
					this.OnFld_Sitestyle_Alerttype_IdChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_Alerttype_Id = value;
					this.SendPropertyChanged("Fld_Sitestyle_Alerttype_Id");
					this.OnFld_Sitestyle_Alerttype_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_Alerttype_Name", DbType="NVarChar(MAX)")]
		public string Fld_Sitestyle_Alerttype_Name
		{
			get
			{
				return this._Fld_Sitestyle_Alerttype_Name;
			}
			set
			{
				if ((this._Fld_Sitestyle_Alerttype_Name != value))
				{
					this.OnFld_Sitestyle_Alerttype_NameChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_Alerttype_Name = value;
					this.SendPropertyChanged("Fld_Sitestyle_Alerttype_Name");
					this.OnFld_Sitestyle_Alerttype_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_Alerttype_Icon", DbType="NVarChar(MAX)")]
		public string Fld_Sitestyle_Alerttype_Icon
		{
			get
			{
				return this._Fld_Sitestyle_Alerttype_Icon;
			}
			set
			{
				if ((this._Fld_Sitestyle_Alerttype_Icon != value))
				{
					this.OnFld_Sitestyle_Alerttype_IconChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_Alerttype_Icon = value;
					this.SendPropertyChanged("Fld_Sitestyle_Alerttype_Icon");
					this.OnFld_Sitestyle_Alerttype_IconChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Sitestyle_Alerttype_Tbl_Sitestyle_Alert", Storage="_Tbl_Sitestyle_Alerts", ThisKey="Fld_Sitestyle_Alerttype_Id", OtherKey="Fld_Sitestyle_Alert_AlerttypeId")]
		public EntitySet<Tbl_Sitestyle_Alert> Tbl_Sitestyle_Alerts
		{
			get
			{
				return this._Tbl_Sitestyle_Alerts;
			}
			set
			{
				this._Tbl_Sitestyle_Alerts.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Sitestyle_Alerts(Tbl_Sitestyle_Alert entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Sitestyle_Alerttype = this;
		}
		
		private void detach_Tbl_Sitestyle_Alerts(Tbl_Sitestyle_Alert entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Sitestyle_Alerttype = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Sitestyle_Css")]
	public partial class Tbl_Sitestyle_Css : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Fld_Sitestyle_Css_Id;
		
		private string _Fld_Sitestyle_Css_Name;
		
		private int _Fld_Sitestyle_Css_LanguageId;
		
		private EntityRef<Tbl_Sitestyle_Language> _Tbl_Sitestyle_Language;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFld_Sitestyle_Css_IdChanging(int value);
    partial void OnFld_Sitestyle_Css_IdChanged();
    partial void OnFld_Sitestyle_Css_NameChanging(string value);
    partial void OnFld_Sitestyle_Css_NameChanged();
    partial void OnFld_Sitestyle_Css_LanguageIdChanging(int value);
    partial void OnFld_Sitestyle_Css_LanguageIdChanged();
    #endregion
		
		public Tbl_Sitestyle_Css()
		{
			this._Tbl_Sitestyle_Language = default(EntityRef<Tbl_Sitestyle_Language>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_Css_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Fld_Sitestyle_Css_Id
		{
			get
			{
				return this._Fld_Sitestyle_Css_Id;
			}
			set
			{
				if ((this._Fld_Sitestyle_Css_Id != value))
				{
					this.OnFld_Sitestyle_Css_IdChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_Css_Id = value;
					this.SendPropertyChanged("Fld_Sitestyle_Css_Id");
					this.OnFld_Sitestyle_Css_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_Css_Name", DbType="NVarChar(MAX)")]
		public string Fld_Sitestyle_Css_Name
		{
			get
			{
				return this._Fld_Sitestyle_Css_Name;
			}
			set
			{
				if ((this._Fld_Sitestyle_Css_Name != value))
				{
					this.OnFld_Sitestyle_Css_NameChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_Css_Name = value;
					this.SendPropertyChanged("Fld_Sitestyle_Css_Name");
					this.OnFld_Sitestyle_Css_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_Css_LanguageId", DbType="Int NOT NULL")]
		public int Fld_Sitestyle_Css_LanguageId
		{
			get
			{
				return this._Fld_Sitestyle_Css_LanguageId;
			}
			set
			{
				if ((this._Fld_Sitestyle_Css_LanguageId != value))
				{
					if (this._Tbl_Sitestyle_Language.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFld_Sitestyle_Css_LanguageIdChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_Css_LanguageId = value;
					this.SendPropertyChanged("Fld_Sitestyle_Css_LanguageId");
					this.OnFld_Sitestyle_Css_LanguageIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Sitestyle_Language_Tbl_Sitestyle_Css", Storage="_Tbl_Sitestyle_Language", ThisKey="Fld_Sitestyle_Css_LanguageId", OtherKey="Fld_Sitestyle_Language_Id", IsForeignKey=true)]
		public Tbl_Sitestyle_Language Tbl_Sitestyle_Language
		{
			get
			{
				return this._Tbl_Sitestyle_Language.Entity;
			}
			set
			{
				Tbl_Sitestyle_Language previousValue = this._Tbl_Sitestyle_Language.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Sitestyle_Language.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Sitestyle_Language.Entity = null;
						previousValue.Tbl_Sitestyle_Csses.Remove(this);
					}
					this._Tbl_Sitestyle_Language.Entity = value;
					if ((value != null))
					{
						value.Tbl_Sitestyle_Csses.Add(this);
						this._Fld_Sitestyle_Css_LanguageId = value.Fld_Sitestyle_Language_Id;
					}
					else
					{
						this._Fld_Sitestyle_Css_LanguageId = default(int);
					}
					this.SendPropertyChanged("Tbl_Sitestyle_Language");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Sitestyle_Font")]
	public partial class Tbl_Sitestyle_Font : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Fld_Sitestyle_Font_Id;
		
		private string _Fld_Sitestyle_Font_Name;
		
		private int _Fld_Sitestyle_Font_LanguageId;
		
		private EntityRef<Tbl_Sitestyle_Language> _Tbl_Sitestyle_Language;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFld_Sitestyle_Font_IdChanging(int value);
    partial void OnFld_Sitestyle_Font_IdChanged();
    partial void OnFld_Sitestyle_Font_NameChanging(string value);
    partial void OnFld_Sitestyle_Font_NameChanged();
    partial void OnFld_Sitestyle_Font_LanguageIdChanging(int value);
    partial void OnFld_Sitestyle_Font_LanguageIdChanged();
    #endregion
		
		public Tbl_Sitestyle_Font()
		{
			this._Tbl_Sitestyle_Language = default(EntityRef<Tbl_Sitestyle_Language>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_Font_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Fld_Sitestyle_Font_Id
		{
			get
			{
				return this._Fld_Sitestyle_Font_Id;
			}
			set
			{
				if ((this._Fld_Sitestyle_Font_Id != value))
				{
					this.OnFld_Sitestyle_Font_IdChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_Font_Id = value;
					this.SendPropertyChanged("Fld_Sitestyle_Font_Id");
					this.OnFld_Sitestyle_Font_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_Font_Name", DbType="NVarChar(MAX)")]
		public string Fld_Sitestyle_Font_Name
		{
			get
			{
				return this._Fld_Sitestyle_Font_Name;
			}
			set
			{
				if ((this._Fld_Sitestyle_Font_Name != value))
				{
					this.OnFld_Sitestyle_Font_NameChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_Font_Name = value;
					this.SendPropertyChanged("Fld_Sitestyle_Font_Name");
					this.OnFld_Sitestyle_Font_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_Font_LanguageId", DbType="Int NOT NULL")]
		public int Fld_Sitestyle_Font_LanguageId
		{
			get
			{
				return this._Fld_Sitestyle_Font_LanguageId;
			}
			set
			{
				if ((this._Fld_Sitestyle_Font_LanguageId != value))
				{
					if (this._Tbl_Sitestyle_Language.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFld_Sitestyle_Font_LanguageIdChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_Font_LanguageId = value;
					this.SendPropertyChanged("Fld_Sitestyle_Font_LanguageId");
					this.OnFld_Sitestyle_Font_LanguageIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Sitestyle_Language_Tbl_Sitestyle_Font", Storage="_Tbl_Sitestyle_Language", ThisKey="Fld_Sitestyle_Font_LanguageId", OtherKey="Fld_Sitestyle_Language_Id", IsForeignKey=true)]
		public Tbl_Sitestyle_Language Tbl_Sitestyle_Language
		{
			get
			{
				return this._Tbl_Sitestyle_Language.Entity;
			}
			set
			{
				Tbl_Sitestyle_Language previousValue = this._Tbl_Sitestyle_Language.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Sitestyle_Language.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Sitestyle_Language.Entity = null;
						previousValue.Tbl_Sitestyle_Fonts.Remove(this);
					}
					this._Tbl_Sitestyle_Language.Entity = value;
					if ((value != null))
					{
						value.Tbl_Sitestyle_Fonts.Add(this);
						this._Fld_Sitestyle_Font_LanguageId = value.Fld_Sitestyle_Language_Id;
					}
					else
					{
						this._Fld_Sitestyle_Font_LanguageId = default(int);
					}
					this.SendPropertyChanged("Tbl_Sitestyle_Language");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Sitestyle_Iso639_1")]
	public partial class Tbl_Sitestyle_Iso639_1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Fld_Sitestyle_Iso639_1_Id;
		
		private string _Fld_Sitestyle_Iso639_1_Code;
		
		private EntitySet<Tbl_Sitestyle_Language> _Tbl_Sitestyle_Languages;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFld_Sitestyle_Iso639_1_IdChanging(int value);
    partial void OnFld_Sitestyle_Iso639_1_IdChanged();
    partial void OnFld_Sitestyle_Iso639_1_CodeChanging(string value);
    partial void OnFld_Sitestyle_Iso639_1_CodeChanged();
    #endregion
		
		public Tbl_Sitestyle_Iso639_1()
		{
			this._Tbl_Sitestyle_Languages = new EntitySet<Tbl_Sitestyle_Language>(new Action<Tbl_Sitestyle_Language>(this.attach_Tbl_Sitestyle_Languages), new Action<Tbl_Sitestyle_Language>(this.detach_Tbl_Sitestyle_Languages));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_Iso639_1_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Fld_Sitestyle_Iso639_1_Id
		{
			get
			{
				return this._Fld_Sitestyle_Iso639_1_Id;
			}
			set
			{
				if ((this._Fld_Sitestyle_Iso639_1_Id != value))
				{
					this.OnFld_Sitestyle_Iso639_1_IdChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_Iso639_1_Id = value;
					this.SendPropertyChanged("Fld_Sitestyle_Iso639_1_Id");
					this.OnFld_Sitestyle_Iso639_1_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_Iso639_1_Code", DbType="NVarChar(MAX)")]
		public string Fld_Sitestyle_Iso639_1_Code
		{
			get
			{
				return this._Fld_Sitestyle_Iso639_1_Code;
			}
			set
			{
				if ((this._Fld_Sitestyle_Iso639_1_Code != value))
				{
					this.OnFld_Sitestyle_Iso639_1_CodeChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_Iso639_1_Code = value;
					this.SendPropertyChanged("Fld_Sitestyle_Iso639_1_Code");
					this.OnFld_Sitestyle_Iso639_1_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Sitestyle_Iso639_1_Tbl_Sitestyle_Language", Storage="_Tbl_Sitestyle_Languages", ThisKey="Fld_Sitestyle_Iso639_1_Id", OtherKey="Fld_Sitestyle_Language_Iso639_1_Id")]
		public EntitySet<Tbl_Sitestyle_Language> Tbl_Sitestyle_Languages
		{
			get
			{
				return this._Tbl_Sitestyle_Languages;
			}
			set
			{
				this._Tbl_Sitestyle_Languages.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Sitestyle_Languages(Tbl_Sitestyle_Language entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Sitestyle_Iso639_1 = this;
		}
		
		private void detach_Tbl_Sitestyle_Languages(Tbl_Sitestyle_Language entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Sitestyle_Iso639_1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Sitestyle_Iso639_2")]
	public partial class Tbl_Sitestyle_Iso639_2 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Fld_Sitestyle_Iso639_2_Id;
		
		private string _Fld_Sitestyle_Iso639_2_Code;
		
		private EntitySet<Tbl_Sitestyle_Language> _Tbl_Sitestyle_Languages;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFld_Sitestyle_Iso639_2_IdChanging(int value);
    partial void OnFld_Sitestyle_Iso639_2_IdChanged();
    partial void OnFld_Sitestyle_Iso639_2_CodeChanging(string value);
    partial void OnFld_Sitestyle_Iso639_2_CodeChanged();
    #endregion
		
		public Tbl_Sitestyle_Iso639_2()
		{
			this._Tbl_Sitestyle_Languages = new EntitySet<Tbl_Sitestyle_Language>(new Action<Tbl_Sitestyle_Language>(this.attach_Tbl_Sitestyle_Languages), new Action<Tbl_Sitestyle_Language>(this.detach_Tbl_Sitestyle_Languages));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_Iso639_2_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Fld_Sitestyle_Iso639_2_Id
		{
			get
			{
				return this._Fld_Sitestyle_Iso639_2_Id;
			}
			set
			{
				if ((this._Fld_Sitestyle_Iso639_2_Id != value))
				{
					this.OnFld_Sitestyle_Iso639_2_IdChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_Iso639_2_Id = value;
					this.SendPropertyChanged("Fld_Sitestyle_Iso639_2_Id");
					this.OnFld_Sitestyle_Iso639_2_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_Iso639_2_Code", DbType="NVarChar(MAX)")]
		public string Fld_Sitestyle_Iso639_2_Code
		{
			get
			{
				return this._Fld_Sitestyle_Iso639_2_Code;
			}
			set
			{
				if ((this._Fld_Sitestyle_Iso639_2_Code != value))
				{
					this.OnFld_Sitestyle_Iso639_2_CodeChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_Iso639_2_Code = value;
					this.SendPropertyChanged("Fld_Sitestyle_Iso639_2_Code");
					this.OnFld_Sitestyle_Iso639_2_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Sitestyle_Iso639_2_Tbl_Sitestyle_Language", Storage="_Tbl_Sitestyle_Languages", ThisKey="Fld_Sitestyle_Iso639_2_Id", OtherKey="Fld_Sitestyle_Language_Iso639_2_Id")]
		public EntitySet<Tbl_Sitestyle_Language> Tbl_Sitestyle_Languages
		{
			get
			{
				return this._Tbl_Sitestyle_Languages;
			}
			set
			{
				this._Tbl_Sitestyle_Languages.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Sitestyle_Languages(Tbl_Sitestyle_Language entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Sitestyle_Iso639_2 = this;
		}
		
		private void detach_Tbl_Sitestyle_Languages(Tbl_Sitestyle_Language entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Sitestyle_Iso639_2 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Sitestyle_Iso639_3")]
	public partial class Tbl_Sitestyle_Iso639_3 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Fld_Sitestyle_Iso639_3_Id;
		
		private string _Fld_Sitestyle_Iso639_3_Code;
		
		private EntitySet<Tbl_Sitestyle_Language> _Tbl_Sitestyle_Languages;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFld_Sitestyle_Iso639_3_IdChanging(int value);
    partial void OnFld_Sitestyle_Iso639_3_IdChanged();
    partial void OnFld_Sitestyle_Iso639_3_CodeChanging(string value);
    partial void OnFld_Sitestyle_Iso639_3_CodeChanged();
    #endregion
		
		public Tbl_Sitestyle_Iso639_3()
		{
			this._Tbl_Sitestyle_Languages = new EntitySet<Tbl_Sitestyle_Language>(new Action<Tbl_Sitestyle_Language>(this.attach_Tbl_Sitestyle_Languages), new Action<Tbl_Sitestyle_Language>(this.detach_Tbl_Sitestyle_Languages));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_Iso639_3_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Fld_Sitestyle_Iso639_3_Id
		{
			get
			{
				return this._Fld_Sitestyle_Iso639_3_Id;
			}
			set
			{
				if ((this._Fld_Sitestyle_Iso639_3_Id != value))
				{
					this.OnFld_Sitestyle_Iso639_3_IdChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_Iso639_3_Id = value;
					this.SendPropertyChanged("Fld_Sitestyle_Iso639_3_Id");
					this.OnFld_Sitestyle_Iso639_3_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_Iso639_3_Code", DbType="NVarChar(MAX)")]
		public string Fld_Sitestyle_Iso639_3_Code
		{
			get
			{
				return this._Fld_Sitestyle_Iso639_3_Code;
			}
			set
			{
				if ((this._Fld_Sitestyle_Iso639_3_Code != value))
				{
					this.OnFld_Sitestyle_Iso639_3_CodeChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_Iso639_3_Code = value;
					this.SendPropertyChanged("Fld_Sitestyle_Iso639_3_Code");
					this.OnFld_Sitestyle_Iso639_3_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Sitestyle_Iso639_3_Tbl_Sitestyle_Language", Storage="_Tbl_Sitestyle_Languages", ThisKey="Fld_Sitestyle_Iso639_3_Id", OtherKey="Fld_Sitestyle_Language_Iso639_3_Id")]
		public EntitySet<Tbl_Sitestyle_Language> Tbl_Sitestyle_Languages
		{
			get
			{
				return this._Tbl_Sitestyle_Languages;
			}
			set
			{
				this._Tbl_Sitestyle_Languages.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Sitestyle_Languages(Tbl_Sitestyle_Language entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Sitestyle_Iso639_3 = this;
		}
		
		private void detach_Tbl_Sitestyle_Languages(Tbl_Sitestyle_Language entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Sitestyle_Iso639_3 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Sitestyle_Language")]
	public partial class Tbl_Sitestyle_Language : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Fld_Sitestyle_Language_Id;
		
		private string _Fld_Sitestyle_Language_Text;
		
		private string _Fld_Sitestyle_Language_Direction;
		
		private int _Fld_Sitestyle_Language_Iso639_1_Id;
		
		private int _Fld_Sitestyle_Language_Iso639_2_Id;
		
		private int _Fld_Sitestyle_Language_Iso639_3_Id;
		
		private EntitySet<Tbl_Sitestyle_AlertLanguage> _Tbl_Sitestyle_AlertLanguages;
		
		private EntitySet<Tbl_Sitestyle_Css> _Tbl_Sitestyle_Csses;
		
		private EntitySet<Tbl_Sitestyle_Font> _Tbl_Sitestyle_Fonts;
		
		private EntitySet<Tbl_Sitestyle_MenuLanguage> _Tbl_Sitestyle_MenuLanguages;
		
		private EntitySet<Tbl_Sitestyle_Metadata> _Tbl_Sitestyle_Metadatas;
		
		private EntitySet<Tbl_Users_UsersActivityGroupLanguage> _Tbl_Users_UsersActivityGroupLanguages;
		
		private EntityRef<Tbl_Sitestyle_Iso639_1> _Tbl_Sitestyle_Iso639_1;
		
		private EntityRef<Tbl_Sitestyle_Iso639_2> _Tbl_Sitestyle_Iso639_2;
		
		private EntityRef<Tbl_Sitestyle_Iso639_3> _Tbl_Sitestyle_Iso639_3;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFld_Sitestyle_Language_IdChanging(int value);
    partial void OnFld_Sitestyle_Language_IdChanged();
    partial void OnFld_Sitestyle_Language_TextChanging(string value);
    partial void OnFld_Sitestyle_Language_TextChanged();
    partial void OnFld_Sitestyle_Language_DirectionChanging(string value);
    partial void OnFld_Sitestyle_Language_DirectionChanged();
    partial void OnFld_Sitestyle_Language_Iso639_1_IdChanging(int value);
    partial void OnFld_Sitestyle_Language_Iso639_1_IdChanged();
    partial void OnFld_Sitestyle_Language_Iso639_2_IdChanging(int value);
    partial void OnFld_Sitestyle_Language_Iso639_2_IdChanged();
    partial void OnFld_Sitestyle_Language_Iso639_3_IdChanging(int value);
    partial void OnFld_Sitestyle_Language_Iso639_3_IdChanged();
    #endregion
		
		public Tbl_Sitestyle_Language()
		{
			this._Tbl_Sitestyle_AlertLanguages = new EntitySet<Tbl_Sitestyle_AlertLanguage>(new Action<Tbl_Sitestyle_AlertLanguage>(this.attach_Tbl_Sitestyle_AlertLanguages), new Action<Tbl_Sitestyle_AlertLanguage>(this.detach_Tbl_Sitestyle_AlertLanguages));
			this._Tbl_Sitestyle_Csses = new EntitySet<Tbl_Sitestyle_Css>(new Action<Tbl_Sitestyle_Css>(this.attach_Tbl_Sitestyle_Csses), new Action<Tbl_Sitestyle_Css>(this.detach_Tbl_Sitestyle_Csses));
			this._Tbl_Sitestyle_Fonts = new EntitySet<Tbl_Sitestyle_Font>(new Action<Tbl_Sitestyle_Font>(this.attach_Tbl_Sitestyle_Fonts), new Action<Tbl_Sitestyle_Font>(this.detach_Tbl_Sitestyle_Fonts));
			this._Tbl_Sitestyle_MenuLanguages = new EntitySet<Tbl_Sitestyle_MenuLanguage>(new Action<Tbl_Sitestyle_MenuLanguage>(this.attach_Tbl_Sitestyle_MenuLanguages), new Action<Tbl_Sitestyle_MenuLanguage>(this.detach_Tbl_Sitestyle_MenuLanguages));
			this._Tbl_Sitestyle_Metadatas = new EntitySet<Tbl_Sitestyle_Metadata>(new Action<Tbl_Sitestyle_Metadata>(this.attach_Tbl_Sitestyle_Metadatas), new Action<Tbl_Sitestyle_Metadata>(this.detach_Tbl_Sitestyle_Metadatas));
			this._Tbl_Users_UsersActivityGroupLanguages = new EntitySet<Tbl_Users_UsersActivityGroupLanguage>(new Action<Tbl_Users_UsersActivityGroupLanguage>(this.attach_Tbl_Users_UsersActivityGroupLanguages), new Action<Tbl_Users_UsersActivityGroupLanguage>(this.detach_Tbl_Users_UsersActivityGroupLanguages));
			this._Tbl_Sitestyle_Iso639_1 = default(EntityRef<Tbl_Sitestyle_Iso639_1>);
			this._Tbl_Sitestyle_Iso639_2 = default(EntityRef<Tbl_Sitestyle_Iso639_2>);
			this._Tbl_Sitestyle_Iso639_3 = default(EntityRef<Tbl_Sitestyle_Iso639_3>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_Language_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Fld_Sitestyle_Language_Id
		{
			get
			{
				return this._Fld_Sitestyle_Language_Id;
			}
			set
			{
				if ((this._Fld_Sitestyle_Language_Id != value))
				{
					this.OnFld_Sitestyle_Language_IdChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_Language_Id = value;
					this.SendPropertyChanged("Fld_Sitestyle_Language_Id");
					this.OnFld_Sitestyle_Language_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_Language_Text", DbType="NVarChar(MAX)")]
		public string Fld_Sitestyle_Language_Text
		{
			get
			{
				return this._Fld_Sitestyle_Language_Text;
			}
			set
			{
				if ((this._Fld_Sitestyle_Language_Text != value))
				{
					this.OnFld_Sitestyle_Language_TextChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_Language_Text = value;
					this.SendPropertyChanged("Fld_Sitestyle_Language_Text");
					this.OnFld_Sitestyle_Language_TextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_Language_Direction", DbType="NVarChar(MAX)")]
		public string Fld_Sitestyle_Language_Direction
		{
			get
			{
				return this._Fld_Sitestyle_Language_Direction;
			}
			set
			{
				if ((this._Fld_Sitestyle_Language_Direction != value))
				{
					this.OnFld_Sitestyle_Language_DirectionChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_Language_Direction = value;
					this.SendPropertyChanged("Fld_Sitestyle_Language_Direction");
					this.OnFld_Sitestyle_Language_DirectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_Language_Iso639_1_Id", DbType="Int NOT NULL")]
		public int Fld_Sitestyle_Language_Iso639_1_Id
		{
			get
			{
				return this._Fld_Sitestyle_Language_Iso639_1_Id;
			}
			set
			{
				if ((this._Fld_Sitestyle_Language_Iso639_1_Id != value))
				{
					if (this._Tbl_Sitestyle_Iso639_1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFld_Sitestyle_Language_Iso639_1_IdChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_Language_Iso639_1_Id = value;
					this.SendPropertyChanged("Fld_Sitestyle_Language_Iso639_1_Id");
					this.OnFld_Sitestyle_Language_Iso639_1_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_Language_Iso639_2_Id", DbType="Int NOT NULL")]
		public int Fld_Sitestyle_Language_Iso639_2_Id
		{
			get
			{
				return this._Fld_Sitestyle_Language_Iso639_2_Id;
			}
			set
			{
				if ((this._Fld_Sitestyle_Language_Iso639_2_Id != value))
				{
					if (this._Tbl_Sitestyle_Iso639_2.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFld_Sitestyle_Language_Iso639_2_IdChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_Language_Iso639_2_Id = value;
					this.SendPropertyChanged("Fld_Sitestyle_Language_Iso639_2_Id");
					this.OnFld_Sitestyle_Language_Iso639_2_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_Language_Iso639_3_Id", DbType="Int NOT NULL")]
		public int Fld_Sitestyle_Language_Iso639_3_Id
		{
			get
			{
				return this._Fld_Sitestyle_Language_Iso639_3_Id;
			}
			set
			{
				if ((this._Fld_Sitestyle_Language_Iso639_3_Id != value))
				{
					if (this._Tbl_Sitestyle_Iso639_3.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFld_Sitestyle_Language_Iso639_3_IdChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_Language_Iso639_3_Id = value;
					this.SendPropertyChanged("Fld_Sitestyle_Language_Iso639_3_Id");
					this.OnFld_Sitestyle_Language_Iso639_3_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Sitestyle_Language_Tbl_Sitestyle_AlertLanguage", Storage="_Tbl_Sitestyle_AlertLanguages", ThisKey="Fld_Sitestyle_Language_Id", OtherKey="Fld_Sitestyle_AlertLanguage_LanguageId")]
		public EntitySet<Tbl_Sitestyle_AlertLanguage> Tbl_Sitestyle_AlertLanguages
		{
			get
			{
				return this._Tbl_Sitestyle_AlertLanguages;
			}
			set
			{
				this._Tbl_Sitestyle_AlertLanguages.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Sitestyle_Language_Tbl_Sitestyle_Css", Storage="_Tbl_Sitestyle_Csses", ThisKey="Fld_Sitestyle_Language_Id", OtherKey="Fld_Sitestyle_Css_LanguageId")]
		public EntitySet<Tbl_Sitestyle_Css> Tbl_Sitestyle_Csses
		{
			get
			{
				return this._Tbl_Sitestyle_Csses;
			}
			set
			{
				this._Tbl_Sitestyle_Csses.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Sitestyle_Language_Tbl_Sitestyle_Font", Storage="_Tbl_Sitestyle_Fonts", ThisKey="Fld_Sitestyle_Language_Id", OtherKey="Fld_Sitestyle_Font_LanguageId")]
		public EntitySet<Tbl_Sitestyle_Font> Tbl_Sitestyle_Fonts
		{
			get
			{
				return this._Tbl_Sitestyle_Fonts;
			}
			set
			{
				this._Tbl_Sitestyle_Fonts.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Sitestyle_Language_Tbl_Sitestyle_MenuLanguage", Storage="_Tbl_Sitestyle_MenuLanguages", ThisKey="Fld_Sitestyle_Language_Id", OtherKey="Fld_Sitestyle_MenuLanguage_LanguageId")]
		public EntitySet<Tbl_Sitestyle_MenuLanguage> Tbl_Sitestyle_MenuLanguages
		{
			get
			{
				return this._Tbl_Sitestyle_MenuLanguages;
			}
			set
			{
				this._Tbl_Sitestyle_MenuLanguages.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Sitestyle_Language_Tbl_Sitestyle_Metadata", Storage="_Tbl_Sitestyle_Metadatas", ThisKey="Fld_Sitestyle_Language_Id", OtherKey="Fld_Sitestyle_Metadata_LanguageId")]
		public EntitySet<Tbl_Sitestyle_Metadata> Tbl_Sitestyle_Metadatas
		{
			get
			{
				return this._Tbl_Sitestyle_Metadatas;
			}
			set
			{
				this._Tbl_Sitestyle_Metadatas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Sitestyle_Language_Tbl_Users_UsersActivityGroupLanguage", Storage="_Tbl_Users_UsersActivityGroupLanguages", ThisKey="Fld_Sitestyle_Language_Id", OtherKey="Fld_Users_UsersActivityGroupLanguage_LanguageId")]
		public EntitySet<Tbl_Users_UsersActivityGroupLanguage> Tbl_Users_UsersActivityGroupLanguages
		{
			get
			{
				return this._Tbl_Users_UsersActivityGroupLanguages;
			}
			set
			{
				this._Tbl_Users_UsersActivityGroupLanguages.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Sitestyle_Iso639_1_Tbl_Sitestyle_Language", Storage="_Tbl_Sitestyle_Iso639_1", ThisKey="Fld_Sitestyle_Language_Iso639_1_Id", OtherKey="Fld_Sitestyle_Iso639_1_Id", IsForeignKey=true)]
		public Tbl_Sitestyle_Iso639_1 Tbl_Sitestyle_Iso639_1
		{
			get
			{
				return this._Tbl_Sitestyle_Iso639_1.Entity;
			}
			set
			{
				Tbl_Sitestyle_Iso639_1 previousValue = this._Tbl_Sitestyle_Iso639_1.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Sitestyle_Iso639_1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Sitestyle_Iso639_1.Entity = null;
						previousValue.Tbl_Sitestyle_Languages.Remove(this);
					}
					this._Tbl_Sitestyle_Iso639_1.Entity = value;
					if ((value != null))
					{
						value.Tbl_Sitestyle_Languages.Add(this);
						this._Fld_Sitestyle_Language_Iso639_1_Id = value.Fld_Sitestyle_Iso639_1_Id;
					}
					else
					{
						this._Fld_Sitestyle_Language_Iso639_1_Id = default(int);
					}
					this.SendPropertyChanged("Tbl_Sitestyle_Iso639_1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Sitestyle_Iso639_2_Tbl_Sitestyle_Language", Storage="_Tbl_Sitestyle_Iso639_2", ThisKey="Fld_Sitestyle_Language_Iso639_2_Id", OtherKey="Fld_Sitestyle_Iso639_2_Id", IsForeignKey=true)]
		public Tbl_Sitestyle_Iso639_2 Tbl_Sitestyle_Iso639_2
		{
			get
			{
				return this._Tbl_Sitestyle_Iso639_2.Entity;
			}
			set
			{
				Tbl_Sitestyle_Iso639_2 previousValue = this._Tbl_Sitestyle_Iso639_2.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Sitestyle_Iso639_2.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Sitestyle_Iso639_2.Entity = null;
						previousValue.Tbl_Sitestyle_Languages.Remove(this);
					}
					this._Tbl_Sitestyle_Iso639_2.Entity = value;
					if ((value != null))
					{
						value.Tbl_Sitestyle_Languages.Add(this);
						this._Fld_Sitestyle_Language_Iso639_2_Id = value.Fld_Sitestyle_Iso639_2_Id;
					}
					else
					{
						this._Fld_Sitestyle_Language_Iso639_2_Id = default(int);
					}
					this.SendPropertyChanged("Tbl_Sitestyle_Iso639_2");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Sitestyle_Iso639_3_Tbl_Sitestyle_Language", Storage="_Tbl_Sitestyle_Iso639_3", ThisKey="Fld_Sitestyle_Language_Iso639_3_Id", OtherKey="Fld_Sitestyle_Iso639_3_Id", IsForeignKey=true)]
		public Tbl_Sitestyle_Iso639_3 Tbl_Sitestyle_Iso639_3
		{
			get
			{
				return this._Tbl_Sitestyle_Iso639_3.Entity;
			}
			set
			{
				Tbl_Sitestyle_Iso639_3 previousValue = this._Tbl_Sitestyle_Iso639_3.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Sitestyle_Iso639_3.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Sitestyle_Iso639_3.Entity = null;
						previousValue.Tbl_Sitestyle_Languages.Remove(this);
					}
					this._Tbl_Sitestyle_Iso639_3.Entity = value;
					if ((value != null))
					{
						value.Tbl_Sitestyle_Languages.Add(this);
						this._Fld_Sitestyle_Language_Iso639_3_Id = value.Fld_Sitestyle_Iso639_3_Id;
					}
					else
					{
						this._Fld_Sitestyle_Language_Iso639_3_Id = default(int);
					}
					this.SendPropertyChanged("Tbl_Sitestyle_Iso639_3");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Sitestyle_AlertLanguages(Tbl_Sitestyle_AlertLanguage entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Sitestyle_Language = this;
		}
		
		private void detach_Tbl_Sitestyle_AlertLanguages(Tbl_Sitestyle_AlertLanguage entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Sitestyle_Language = null;
		}
		
		private void attach_Tbl_Sitestyle_Csses(Tbl_Sitestyle_Css entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Sitestyle_Language = this;
		}
		
		private void detach_Tbl_Sitestyle_Csses(Tbl_Sitestyle_Css entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Sitestyle_Language = null;
		}
		
		private void attach_Tbl_Sitestyle_Fonts(Tbl_Sitestyle_Font entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Sitestyle_Language = this;
		}
		
		private void detach_Tbl_Sitestyle_Fonts(Tbl_Sitestyle_Font entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Sitestyle_Language = null;
		}
		
		private void attach_Tbl_Sitestyle_MenuLanguages(Tbl_Sitestyle_MenuLanguage entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Sitestyle_Language = this;
		}
		
		private void detach_Tbl_Sitestyle_MenuLanguages(Tbl_Sitestyle_MenuLanguage entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Sitestyle_Language = null;
		}
		
		private void attach_Tbl_Sitestyle_Metadatas(Tbl_Sitestyle_Metadata entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Sitestyle_Language = this;
		}
		
		private void detach_Tbl_Sitestyle_Metadatas(Tbl_Sitestyle_Metadata entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Sitestyle_Language = null;
		}
		
		private void attach_Tbl_Users_UsersActivityGroupLanguages(Tbl_Users_UsersActivityGroupLanguage entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Sitestyle_Language = this;
		}
		
		private void detach_Tbl_Users_UsersActivityGroupLanguages(Tbl_Users_UsersActivityGroupLanguage entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Sitestyle_Language = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Sitestyle_Menu")]
	public partial class Tbl_Sitestyle_Menu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Fld_Sitestyle_Menu_Id;
		
		private string _Fld_Sitestyle_Menu_Text;
		
		private string _Fld_Sitestyle_Menu_Hotkey;
		
		private string _Fld_Sitestyle_Menu_FontIcon;
		
		private string _Fld_Sitestyle_Menu_ImageIcon;
		
		private int _Fld_Sitestyle_Menu_AccessId;
		
		private EntitySet<Tbl_Sitestyle_MenuLanguage> _Tbl_Sitestyle_MenuLanguages;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFld_Sitestyle_Menu_IdChanging(int value);
    partial void OnFld_Sitestyle_Menu_IdChanged();
    partial void OnFld_Sitestyle_Menu_TextChanging(string value);
    partial void OnFld_Sitestyle_Menu_TextChanged();
    partial void OnFld_Sitestyle_Menu_HotkeyChanging(string value);
    partial void OnFld_Sitestyle_Menu_HotkeyChanged();
    partial void OnFld_Sitestyle_Menu_FontIconChanging(string value);
    partial void OnFld_Sitestyle_Menu_FontIconChanged();
    partial void OnFld_Sitestyle_Menu_ImageIconChanging(string value);
    partial void OnFld_Sitestyle_Menu_ImageIconChanged();
    partial void OnFld_Sitestyle_Menu_AccessIdChanging(int value);
    partial void OnFld_Sitestyle_Menu_AccessIdChanged();
    #endregion
		
		public Tbl_Sitestyle_Menu()
		{
			this._Tbl_Sitestyle_MenuLanguages = new EntitySet<Tbl_Sitestyle_MenuLanguage>(new Action<Tbl_Sitestyle_MenuLanguage>(this.attach_Tbl_Sitestyle_MenuLanguages), new Action<Tbl_Sitestyle_MenuLanguage>(this.detach_Tbl_Sitestyle_MenuLanguages));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_Menu_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Fld_Sitestyle_Menu_Id
		{
			get
			{
				return this._Fld_Sitestyle_Menu_Id;
			}
			set
			{
				if ((this._Fld_Sitestyle_Menu_Id != value))
				{
					this.OnFld_Sitestyle_Menu_IdChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_Menu_Id = value;
					this.SendPropertyChanged("Fld_Sitestyle_Menu_Id");
					this.OnFld_Sitestyle_Menu_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_Menu_Text", DbType="NVarChar(MAX)")]
		public string Fld_Sitestyle_Menu_Text
		{
			get
			{
				return this._Fld_Sitestyle_Menu_Text;
			}
			set
			{
				if ((this._Fld_Sitestyle_Menu_Text != value))
				{
					this.OnFld_Sitestyle_Menu_TextChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_Menu_Text = value;
					this.SendPropertyChanged("Fld_Sitestyle_Menu_Text");
					this.OnFld_Sitestyle_Menu_TextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_Menu_Hotkey", DbType="NVarChar(MAX)")]
		public string Fld_Sitestyle_Menu_Hotkey
		{
			get
			{
				return this._Fld_Sitestyle_Menu_Hotkey;
			}
			set
			{
				if ((this._Fld_Sitestyle_Menu_Hotkey != value))
				{
					this.OnFld_Sitestyle_Menu_HotkeyChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_Menu_Hotkey = value;
					this.SendPropertyChanged("Fld_Sitestyle_Menu_Hotkey");
					this.OnFld_Sitestyle_Menu_HotkeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_Menu_FontIcon", DbType="NVarChar(MAX)")]
		public string Fld_Sitestyle_Menu_FontIcon
		{
			get
			{
				return this._Fld_Sitestyle_Menu_FontIcon;
			}
			set
			{
				if ((this._Fld_Sitestyle_Menu_FontIcon != value))
				{
					this.OnFld_Sitestyle_Menu_FontIconChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_Menu_FontIcon = value;
					this.SendPropertyChanged("Fld_Sitestyle_Menu_FontIcon");
					this.OnFld_Sitestyle_Menu_FontIconChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_Menu_ImageIcon", DbType="NVarChar(MAX)")]
		public string Fld_Sitestyle_Menu_ImageIcon
		{
			get
			{
				return this._Fld_Sitestyle_Menu_ImageIcon;
			}
			set
			{
				if ((this._Fld_Sitestyle_Menu_ImageIcon != value))
				{
					this.OnFld_Sitestyle_Menu_ImageIconChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_Menu_ImageIcon = value;
					this.SendPropertyChanged("Fld_Sitestyle_Menu_ImageIcon");
					this.OnFld_Sitestyle_Menu_ImageIconChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_Menu_AccessId", DbType="Int NOT NULL")]
		public int Fld_Sitestyle_Menu_AccessId
		{
			get
			{
				return this._Fld_Sitestyle_Menu_AccessId;
			}
			set
			{
				if ((this._Fld_Sitestyle_Menu_AccessId != value))
				{
					this.OnFld_Sitestyle_Menu_AccessIdChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_Menu_AccessId = value;
					this.SendPropertyChanged("Fld_Sitestyle_Menu_AccessId");
					this.OnFld_Sitestyle_Menu_AccessIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Sitestyle_Menu_Tbl_Sitestyle_MenuLanguage", Storage="_Tbl_Sitestyle_MenuLanguages", ThisKey="Fld_Sitestyle_Menu_Id", OtherKey="Fld_Sitestyle_MenuLanguage_MenuId")]
		public EntitySet<Tbl_Sitestyle_MenuLanguage> Tbl_Sitestyle_MenuLanguages
		{
			get
			{
				return this._Tbl_Sitestyle_MenuLanguages;
			}
			set
			{
				this._Tbl_Sitestyle_MenuLanguages.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Sitestyle_MenuLanguages(Tbl_Sitestyle_MenuLanguage entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Sitestyle_Menu = this;
		}
		
		private void detach_Tbl_Sitestyle_MenuLanguages(Tbl_Sitestyle_MenuLanguage entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Sitestyle_Menu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Sitestyle_MenuLanguage")]
	public partial class Tbl_Sitestyle_MenuLanguage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Fld_Sitestyle_MenuLanguage_Id;
		
		private string _Fld_Sitestyle_MenuLanguage_Title;
		
		private string _Fld_Sitestyle_MenuLanguage_Tooltip;
		
		private int _Fld_Sitestyle_MenuLanguage_MenuId;
		
		private int _Fld_Sitestyle_MenuLanguage_LanguageId;
		
		private EntityRef<Tbl_Sitestyle_Language> _Tbl_Sitestyle_Language;
		
		private EntityRef<Tbl_Sitestyle_Menu> _Tbl_Sitestyle_Menu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFld_Sitestyle_MenuLanguage_IdChanging(int value);
    partial void OnFld_Sitestyle_MenuLanguage_IdChanged();
    partial void OnFld_Sitestyle_MenuLanguage_TitleChanging(string value);
    partial void OnFld_Sitestyle_MenuLanguage_TitleChanged();
    partial void OnFld_Sitestyle_MenuLanguage_TooltipChanging(string value);
    partial void OnFld_Sitestyle_MenuLanguage_TooltipChanged();
    partial void OnFld_Sitestyle_MenuLanguage_MenuIdChanging(int value);
    partial void OnFld_Sitestyle_MenuLanguage_MenuIdChanged();
    partial void OnFld_Sitestyle_MenuLanguage_LanguageIdChanging(int value);
    partial void OnFld_Sitestyle_MenuLanguage_LanguageIdChanged();
    #endregion
		
		public Tbl_Sitestyle_MenuLanguage()
		{
			this._Tbl_Sitestyle_Language = default(EntityRef<Tbl_Sitestyle_Language>);
			this._Tbl_Sitestyle_Menu = default(EntityRef<Tbl_Sitestyle_Menu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_MenuLanguage_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Fld_Sitestyle_MenuLanguage_Id
		{
			get
			{
				return this._Fld_Sitestyle_MenuLanguage_Id;
			}
			set
			{
				if ((this._Fld_Sitestyle_MenuLanguage_Id != value))
				{
					this.OnFld_Sitestyle_MenuLanguage_IdChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_MenuLanguage_Id = value;
					this.SendPropertyChanged("Fld_Sitestyle_MenuLanguage_Id");
					this.OnFld_Sitestyle_MenuLanguage_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_MenuLanguage_Title", DbType="NVarChar(MAX)")]
		public string Fld_Sitestyle_MenuLanguage_Title
		{
			get
			{
				return this._Fld_Sitestyle_MenuLanguage_Title;
			}
			set
			{
				if ((this._Fld_Sitestyle_MenuLanguage_Title != value))
				{
					this.OnFld_Sitestyle_MenuLanguage_TitleChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_MenuLanguage_Title = value;
					this.SendPropertyChanged("Fld_Sitestyle_MenuLanguage_Title");
					this.OnFld_Sitestyle_MenuLanguage_TitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_MenuLanguage_Tooltip", DbType="NVarChar(MAX)")]
		public string Fld_Sitestyle_MenuLanguage_Tooltip
		{
			get
			{
				return this._Fld_Sitestyle_MenuLanguage_Tooltip;
			}
			set
			{
				if ((this._Fld_Sitestyle_MenuLanguage_Tooltip != value))
				{
					this.OnFld_Sitestyle_MenuLanguage_TooltipChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_MenuLanguage_Tooltip = value;
					this.SendPropertyChanged("Fld_Sitestyle_MenuLanguage_Tooltip");
					this.OnFld_Sitestyle_MenuLanguage_TooltipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_MenuLanguage_MenuId", DbType="Int NOT NULL")]
		public int Fld_Sitestyle_MenuLanguage_MenuId
		{
			get
			{
				return this._Fld_Sitestyle_MenuLanguage_MenuId;
			}
			set
			{
				if ((this._Fld_Sitestyle_MenuLanguage_MenuId != value))
				{
					if (this._Tbl_Sitestyle_Menu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFld_Sitestyle_MenuLanguage_MenuIdChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_MenuLanguage_MenuId = value;
					this.SendPropertyChanged("Fld_Sitestyle_MenuLanguage_MenuId");
					this.OnFld_Sitestyle_MenuLanguage_MenuIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_MenuLanguage_LanguageId", DbType="Int NOT NULL")]
		public int Fld_Sitestyle_MenuLanguage_LanguageId
		{
			get
			{
				return this._Fld_Sitestyle_MenuLanguage_LanguageId;
			}
			set
			{
				if ((this._Fld_Sitestyle_MenuLanguage_LanguageId != value))
				{
					if (this._Tbl_Sitestyle_Language.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFld_Sitestyle_MenuLanguage_LanguageIdChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_MenuLanguage_LanguageId = value;
					this.SendPropertyChanged("Fld_Sitestyle_MenuLanguage_LanguageId");
					this.OnFld_Sitestyle_MenuLanguage_LanguageIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Sitestyle_Language_Tbl_Sitestyle_MenuLanguage", Storage="_Tbl_Sitestyle_Language", ThisKey="Fld_Sitestyle_MenuLanguage_LanguageId", OtherKey="Fld_Sitestyle_Language_Id", IsForeignKey=true)]
		public Tbl_Sitestyle_Language Tbl_Sitestyle_Language
		{
			get
			{
				return this._Tbl_Sitestyle_Language.Entity;
			}
			set
			{
				Tbl_Sitestyle_Language previousValue = this._Tbl_Sitestyle_Language.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Sitestyle_Language.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Sitestyle_Language.Entity = null;
						previousValue.Tbl_Sitestyle_MenuLanguages.Remove(this);
					}
					this._Tbl_Sitestyle_Language.Entity = value;
					if ((value != null))
					{
						value.Tbl_Sitestyle_MenuLanguages.Add(this);
						this._Fld_Sitestyle_MenuLanguage_LanguageId = value.Fld_Sitestyle_Language_Id;
					}
					else
					{
						this._Fld_Sitestyle_MenuLanguage_LanguageId = default(int);
					}
					this.SendPropertyChanged("Tbl_Sitestyle_Language");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Sitestyle_Menu_Tbl_Sitestyle_MenuLanguage", Storage="_Tbl_Sitestyle_Menu", ThisKey="Fld_Sitestyle_MenuLanguage_MenuId", OtherKey="Fld_Sitestyle_Menu_Id", IsForeignKey=true)]
		public Tbl_Sitestyle_Menu Tbl_Sitestyle_Menu
		{
			get
			{
				return this._Tbl_Sitestyle_Menu.Entity;
			}
			set
			{
				Tbl_Sitestyle_Menu previousValue = this._Tbl_Sitestyle_Menu.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Sitestyle_Menu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Sitestyle_Menu.Entity = null;
						previousValue.Tbl_Sitestyle_MenuLanguages.Remove(this);
					}
					this._Tbl_Sitestyle_Menu.Entity = value;
					if ((value != null))
					{
						value.Tbl_Sitestyle_MenuLanguages.Add(this);
						this._Fld_Sitestyle_MenuLanguage_MenuId = value.Fld_Sitestyle_Menu_Id;
					}
					else
					{
						this._Fld_Sitestyle_MenuLanguage_MenuId = default(int);
					}
					this.SendPropertyChanged("Tbl_Sitestyle_Menu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Sitestyle_Metadata")]
	public partial class Tbl_Sitestyle_Metadata : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Fld_Sitestyle_Metadata_Id;
		
		private string _Fld_Sitestyle_Metadata_Text;
		
		private int _Fld_Sitestyle_Metadata_LanguageId;
		
		private EntityRef<Tbl_Sitestyle_Language> _Tbl_Sitestyle_Language;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFld_Sitestyle_Metadata_IdChanging(int value);
    partial void OnFld_Sitestyle_Metadata_IdChanged();
    partial void OnFld_Sitestyle_Metadata_TextChanging(string value);
    partial void OnFld_Sitestyle_Metadata_TextChanged();
    partial void OnFld_Sitestyle_Metadata_LanguageIdChanging(int value);
    partial void OnFld_Sitestyle_Metadata_LanguageIdChanged();
    #endregion
		
		public Tbl_Sitestyle_Metadata()
		{
			this._Tbl_Sitestyle_Language = default(EntityRef<Tbl_Sitestyle_Language>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_Metadata_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Fld_Sitestyle_Metadata_Id
		{
			get
			{
				return this._Fld_Sitestyle_Metadata_Id;
			}
			set
			{
				if ((this._Fld_Sitestyle_Metadata_Id != value))
				{
					this.OnFld_Sitestyle_Metadata_IdChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_Metadata_Id = value;
					this.SendPropertyChanged("Fld_Sitestyle_Metadata_Id");
					this.OnFld_Sitestyle_Metadata_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_Metadata_Text", DbType="NVarChar(MAX)")]
		public string Fld_Sitestyle_Metadata_Text
		{
			get
			{
				return this._Fld_Sitestyle_Metadata_Text;
			}
			set
			{
				if ((this._Fld_Sitestyle_Metadata_Text != value))
				{
					this.OnFld_Sitestyle_Metadata_TextChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_Metadata_Text = value;
					this.SendPropertyChanged("Fld_Sitestyle_Metadata_Text");
					this.OnFld_Sitestyle_Metadata_TextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Sitestyle_Metadata_LanguageId", DbType="Int NOT NULL")]
		public int Fld_Sitestyle_Metadata_LanguageId
		{
			get
			{
				return this._Fld_Sitestyle_Metadata_LanguageId;
			}
			set
			{
				if ((this._Fld_Sitestyle_Metadata_LanguageId != value))
				{
					if (this._Tbl_Sitestyle_Language.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFld_Sitestyle_Metadata_LanguageIdChanging(value);
					this.SendPropertyChanging();
					this._Fld_Sitestyle_Metadata_LanguageId = value;
					this.SendPropertyChanged("Fld_Sitestyle_Metadata_LanguageId");
					this.OnFld_Sitestyle_Metadata_LanguageIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Sitestyle_Language_Tbl_Sitestyle_Metadata", Storage="_Tbl_Sitestyle_Language", ThisKey="Fld_Sitestyle_Metadata_LanguageId", OtherKey="Fld_Sitestyle_Language_Id", IsForeignKey=true)]
		public Tbl_Sitestyle_Language Tbl_Sitestyle_Language
		{
			get
			{
				return this._Tbl_Sitestyle_Language.Entity;
			}
			set
			{
				Tbl_Sitestyle_Language previousValue = this._Tbl_Sitestyle_Language.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Sitestyle_Language.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Sitestyle_Language.Entity = null;
						previousValue.Tbl_Sitestyle_Metadatas.Remove(this);
					}
					this._Tbl_Sitestyle_Language.Entity = value;
					if ((value != null))
					{
						value.Tbl_Sitestyle_Metadatas.Add(this);
						this._Fld_Sitestyle_Metadata_LanguageId = value.Fld_Sitestyle_Language_Id;
					}
					else
					{
						this._Fld_Sitestyle_Metadata_LanguageId = default(int);
					}
					this.SendPropertyChanged("Tbl_Sitestyle_Language");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Users_UsersActivityGroup")]
	public partial class Tbl_Users_UsersActivityGroup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Fld_Users_UsersActivityGroup_Id;
		
		private string _Fld_Users_UsersActivityGroup_Title;
		
		private EntitySet<Tbl_Users_UsersActivityGroupLanguage> _Tbl_Users_UsersActivityGroupLanguages;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFld_Users_UsersActivityGroup_IdChanging(int value);
    partial void OnFld_Users_UsersActivityGroup_IdChanged();
    partial void OnFld_Users_UsersActivityGroup_TitleChanging(string value);
    partial void OnFld_Users_UsersActivityGroup_TitleChanged();
    #endregion
		
		public Tbl_Users_UsersActivityGroup()
		{
			this._Tbl_Users_UsersActivityGroupLanguages = new EntitySet<Tbl_Users_UsersActivityGroupLanguage>(new Action<Tbl_Users_UsersActivityGroupLanguage>(this.attach_Tbl_Users_UsersActivityGroupLanguages), new Action<Tbl_Users_UsersActivityGroupLanguage>(this.detach_Tbl_Users_UsersActivityGroupLanguages));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Users_UsersActivityGroup_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Fld_Users_UsersActivityGroup_Id
		{
			get
			{
				return this._Fld_Users_UsersActivityGroup_Id;
			}
			set
			{
				if ((this._Fld_Users_UsersActivityGroup_Id != value))
				{
					this.OnFld_Users_UsersActivityGroup_IdChanging(value);
					this.SendPropertyChanging();
					this._Fld_Users_UsersActivityGroup_Id = value;
					this.SendPropertyChanged("Fld_Users_UsersActivityGroup_Id");
					this.OnFld_Users_UsersActivityGroup_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Users_UsersActivityGroup_Title", DbType="NVarChar(MAX)")]
		public string Fld_Users_UsersActivityGroup_Title
		{
			get
			{
				return this._Fld_Users_UsersActivityGroup_Title;
			}
			set
			{
				if ((this._Fld_Users_UsersActivityGroup_Title != value))
				{
					this.OnFld_Users_UsersActivityGroup_TitleChanging(value);
					this.SendPropertyChanging();
					this._Fld_Users_UsersActivityGroup_Title = value;
					this.SendPropertyChanged("Fld_Users_UsersActivityGroup_Title");
					this.OnFld_Users_UsersActivityGroup_TitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Users_UsersActivityGroup_Tbl_Users_UsersActivityGroupLanguage", Storage="_Tbl_Users_UsersActivityGroupLanguages", ThisKey="Fld_Users_UsersActivityGroup_Id", OtherKey="Fld_Users_UsersActivityGroupLanguage_UsersActivityGroupId")]
		public EntitySet<Tbl_Users_UsersActivityGroupLanguage> Tbl_Users_UsersActivityGroupLanguages
		{
			get
			{
				return this._Tbl_Users_UsersActivityGroupLanguages;
			}
			set
			{
				this._Tbl_Users_UsersActivityGroupLanguages.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Users_UsersActivityGroupLanguages(Tbl_Users_UsersActivityGroupLanguage entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Users_UsersActivityGroup = this;
		}
		
		private void detach_Tbl_Users_UsersActivityGroupLanguages(Tbl_Users_UsersActivityGroupLanguage entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Users_UsersActivityGroup = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Users_UsersActivityGroupLanguage")]
	public partial class Tbl_Users_UsersActivityGroupLanguage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Fld_Users_UsersActivityGroupLanguage_Id;
		
		private string _Fld_Users_UsersActivityGroupLanguage_Title;
		
		private int _Fld_Users_UsersActivityGroupLanguage_UsersActivityGroupId;
		
		private int _Fld_Users_UsersActivityGroupLanguage_LanguageId;
		
		private EntityRef<Tbl_Sitestyle_Language> _Tbl_Sitestyle_Language;
		
		private EntityRef<Tbl_Users_UsersActivityGroup> _Tbl_Users_UsersActivityGroup;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFld_Users_UsersActivityGroupLanguage_IdChanging(int value);
    partial void OnFld_Users_UsersActivityGroupLanguage_IdChanged();
    partial void OnFld_Users_UsersActivityGroupLanguage_TitleChanging(string value);
    partial void OnFld_Users_UsersActivityGroupLanguage_TitleChanged();
    partial void OnFld_Users_UsersActivityGroupLanguage_UsersActivityGroupIdChanging(int value);
    partial void OnFld_Users_UsersActivityGroupLanguage_UsersActivityGroupIdChanged();
    partial void OnFld_Users_UsersActivityGroupLanguage_LanguageIdChanging(int value);
    partial void OnFld_Users_UsersActivityGroupLanguage_LanguageIdChanged();
    #endregion
		
		public Tbl_Users_UsersActivityGroupLanguage()
		{
			this._Tbl_Sitestyle_Language = default(EntityRef<Tbl_Sitestyle_Language>);
			this._Tbl_Users_UsersActivityGroup = default(EntityRef<Tbl_Users_UsersActivityGroup>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Users_UsersActivityGroupLanguage_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Fld_Users_UsersActivityGroupLanguage_Id
		{
			get
			{
				return this._Fld_Users_UsersActivityGroupLanguage_Id;
			}
			set
			{
				if ((this._Fld_Users_UsersActivityGroupLanguage_Id != value))
				{
					this.OnFld_Users_UsersActivityGroupLanguage_IdChanging(value);
					this.SendPropertyChanging();
					this._Fld_Users_UsersActivityGroupLanguage_Id = value;
					this.SendPropertyChanged("Fld_Users_UsersActivityGroupLanguage_Id");
					this.OnFld_Users_UsersActivityGroupLanguage_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Users_UsersActivityGroupLanguage_Title", DbType="NVarChar(MAX)")]
		public string Fld_Users_UsersActivityGroupLanguage_Title
		{
			get
			{
				return this._Fld_Users_UsersActivityGroupLanguage_Title;
			}
			set
			{
				if ((this._Fld_Users_UsersActivityGroupLanguage_Title != value))
				{
					this.OnFld_Users_UsersActivityGroupLanguage_TitleChanging(value);
					this.SendPropertyChanging();
					this._Fld_Users_UsersActivityGroupLanguage_Title = value;
					this.SendPropertyChanged("Fld_Users_UsersActivityGroupLanguage_Title");
					this.OnFld_Users_UsersActivityGroupLanguage_TitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Users_UsersActivityGroupLanguage_UsersActivityGroupId", DbType="Int NOT NULL")]
		public int Fld_Users_UsersActivityGroupLanguage_UsersActivityGroupId
		{
			get
			{
				return this._Fld_Users_UsersActivityGroupLanguage_UsersActivityGroupId;
			}
			set
			{
				if ((this._Fld_Users_UsersActivityGroupLanguage_UsersActivityGroupId != value))
				{
					if (this._Tbl_Users_UsersActivityGroup.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFld_Users_UsersActivityGroupLanguage_UsersActivityGroupIdChanging(value);
					this.SendPropertyChanging();
					this._Fld_Users_UsersActivityGroupLanguage_UsersActivityGroupId = value;
					this.SendPropertyChanged("Fld_Users_UsersActivityGroupLanguage_UsersActivityGroupId");
					this.OnFld_Users_UsersActivityGroupLanguage_UsersActivityGroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fld_Users_UsersActivityGroupLanguage_LanguageId", DbType="Int NOT NULL")]
		public int Fld_Users_UsersActivityGroupLanguage_LanguageId
		{
			get
			{
				return this._Fld_Users_UsersActivityGroupLanguage_LanguageId;
			}
			set
			{
				if ((this._Fld_Users_UsersActivityGroupLanguage_LanguageId != value))
				{
					if (this._Tbl_Sitestyle_Language.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFld_Users_UsersActivityGroupLanguage_LanguageIdChanging(value);
					this.SendPropertyChanging();
					this._Fld_Users_UsersActivityGroupLanguage_LanguageId = value;
					this.SendPropertyChanged("Fld_Users_UsersActivityGroupLanguage_LanguageId");
					this.OnFld_Users_UsersActivityGroupLanguage_LanguageIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Sitestyle_Language_Tbl_Users_UsersActivityGroupLanguage", Storage="_Tbl_Sitestyle_Language", ThisKey="Fld_Users_UsersActivityGroupLanguage_LanguageId", OtherKey="Fld_Sitestyle_Language_Id", IsForeignKey=true)]
		public Tbl_Sitestyle_Language Tbl_Sitestyle_Language
		{
			get
			{
				return this._Tbl_Sitestyle_Language.Entity;
			}
			set
			{
				Tbl_Sitestyle_Language previousValue = this._Tbl_Sitestyle_Language.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Sitestyle_Language.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Sitestyle_Language.Entity = null;
						previousValue.Tbl_Users_UsersActivityGroupLanguages.Remove(this);
					}
					this._Tbl_Sitestyle_Language.Entity = value;
					if ((value != null))
					{
						value.Tbl_Users_UsersActivityGroupLanguages.Add(this);
						this._Fld_Users_UsersActivityGroupLanguage_LanguageId = value.Fld_Sitestyle_Language_Id;
					}
					else
					{
						this._Fld_Users_UsersActivityGroupLanguage_LanguageId = default(int);
					}
					this.SendPropertyChanged("Tbl_Sitestyle_Language");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Users_UsersActivityGroup_Tbl_Users_UsersActivityGroupLanguage", Storage="_Tbl_Users_UsersActivityGroup", ThisKey="Fld_Users_UsersActivityGroupLanguage_UsersActivityGroupId", OtherKey="Fld_Users_UsersActivityGroup_Id", IsForeignKey=true)]
		public Tbl_Users_UsersActivityGroup Tbl_Users_UsersActivityGroup
		{
			get
			{
				return this._Tbl_Users_UsersActivityGroup.Entity;
			}
			set
			{
				Tbl_Users_UsersActivityGroup previousValue = this._Tbl_Users_UsersActivityGroup.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Users_UsersActivityGroup.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Users_UsersActivityGroup.Entity = null;
						previousValue.Tbl_Users_UsersActivityGroupLanguages.Remove(this);
					}
					this._Tbl_Users_UsersActivityGroup.Entity = value;
					if ((value != null))
					{
						value.Tbl_Users_UsersActivityGroupLanguages.Add(this);
						this._Fld_Users_UsersActivityGroupLanguage_UsersActivityGroupId = value.Fld_Users_UsersActivityGroup_Id;
					}
					else
					{
						this._Fld_Users_UsersActivityGroupLanguage_UsersActivityGroupId = default(int);
					}
					this.SendPropertyChanged("Tbl_Users_UsersActivityGroup");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
